name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build de la imagen
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-proyecto:latest .

    - name: Push de la imagen a Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-proyecto:latest
